name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AIRFLOW_IMAGE_NAME: apache/airflow:2.10.2
  AIRFLOW_UID: 50000
  AIRFLOW_PROJ_DIR: .
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow
  POSTGRES_DB: airflow
  _AIRFLOW_WWW_USER_USERNAME: airflow
  _AIRFLOW_WWW_USER_PASSWORD: airflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          AIRFLOW_IMAGE_NAME: ${{ env.AIRFLOW_IMAGE_NAME }}
        run: |
          docker build -t $AIRFLOW_IMAGE_NAME .
          docker tag $AIRFLOW_IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/my-airflow-project:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-airflow-project:latest

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        run: |
          python -m pytest tests/

  deploy:
    runs-on: ubuntu-latest

    needs: [build, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-airflow-project:latest .

      - name: Push the Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-airflow-project:latest
